---
- name: Update package metadata
  ansible.builtin.dnf:
    update_cache: true

- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present

- name: Ensure SSH service is enabled
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started
